  
name: TEST

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/DEPLOY.yml'
      - '.gitignore'

env:
  NO_HEADLESS_TEST: true

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: CALL gradlew.bat --stacktrace --no-daemon jvmTest
        shell: cmd

  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: ./gradlew --stacktrace --no-daemon jvmTest

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: ./gradlew --stacktrace --no-daemon jvmTest
